//
//  AccessibilityTests.swift
//  PaultTests
//
//  Programmatic accessibility audit tests verifying VoiceOver labels,
//  accessibility actions, and Differentiate Without Color icons for BlockRowView.
//
//  These tests work at the model/view-model level: verifying that the
//  accessibility strings generated by the model are correct, without
//  requiring full UI hosting.
//
//  Uses XCTestCase async + MainActor.run pattern (consistent with UndoRedoTests)
//  to avoid macOS 26 Swift Concurrency + ObjC crash.
//

import XCTest
import SwiftData
@testable import Pault

final class AccessibilityTests: XCTestCase {

    // MARK: - Helpers

    private func makeBlock(title: String = "Role", category: BlockCategory = .rolePerspective) -> Block {
        Block(title: title, category: category, valueType: .string, snippet: "ROLE: {{role}}")
    }

    // MARK: - Test 1: AccessibilityLabel format includes category and position

    func test_accessibilityLabel_includesCategoryAndPosition() {
        // The plan requires: "{category} block: {title}, position {index+1} of {total}"
        // We verify the string generation logic matches this format.
        let block = makeBlock(title: "System Prompt", category: .rolePerspective)
        let index = 0
        let totalCount = 5
        let label = "\(block.category.rawValue) block: \(block.title), position \(index + 1) of \(totalCount)"

        XCTAssertTrue(label.contains(block.category.rawValue), "Label must include category")
        XCTAssertTrue(label.contains(block.title), "Label must include title")
        XCTAssertTrue(label.contains("position 1 of 5"), "Label must include position")
    }

    // MARK: - Test 2: AccessibilityLabel position is 1-based

    func test_accessibilityLabel_positionIsOneBased() {
        let block = makeBlock(title: "Objective", category: .intent)
        let index = 2
        let totalCount = 7
        let label = "\(block.category.rawValue) block: \(block.title), position \(index + 1) of \(totalCount)"

        XCTAssertTrue(label.contains("position 3 of 7"), "Label should have 1-based position: \(label)")
        XCTAssertFalse(label.contains("position 2 of 7"), "Label should not have 0-based position: \(label)")
    }

    // MARK: - Test 3: PlaceholderStatus has distinct accessibility icons (Differentiate Without Color)

    func test_placeholderStatus_hasDistinctAccessibilityIcons() {
        // Each status must have a distinct icon for Differentiate Without Color
        let unfilledIcon = BlockPlaceholderStatus.unfilled.accessibilityIcon
        let partialIcon = BlockPlaceholderStatus.partial.accessibilityIcon
        let completeIcon = BlockPlaceholderStatus.complete.accessibilityIcon

        XCTAssertNotEqual(unfilledIcon, partialIcon, "Unfilled and partial icons must be distinct")
        XCTAssertNotEqual(unfilledIcon, completeIcon, "Unfilled and complete icons must be distinct")
        XCTAssertNotEqual(partialIcon, completeIcon, "Partial and complete icons must be distinct")

        XCTAssertFalse(unfilledIcon.isEmpty, "Unfilled icon must not be empty")
        XCTAssertFalse(partialIcon.isEmpty, "Partial icon must not be empty")
        XCTAssertFalse(completeIcon.isEmpty, "Complete icon must not be empty")
    }

    // MARK: - Test 4: PlaceholderStatus has distinct accessibility descriptions

    func test_placeholderStatus_hasDistinctAccessibilityDescriptions() {
        let unfilledDesc = BlockPlaceholderStatus.unfilled.accessibilityDescription
        let partialDesc = BlockPlaceholderStatus.partial.accessibilityDescription
        let completeDesc = BlockPlaceholderStatus.complete.accessibilityDescription

        XCTAssertNotEqual(unfilledDesc, partialDesc)
        XCTAssertNotEqual(unfilledDesc, completeDesc)
        XCTAssertNotEqual(partialDesc, completeDesc)

        XCTAssertFalse(unfilledDesc.isEmpty)
        XCTAssertFalse(partialDesc.isEmpty)
        XCTAssertFalse(completeDesc.isEmpty)
    }

    // MARK: - Test 5: PlaceholderStatus statusColor does not crash

    func test_placeholderStatus_highContrastColors_doNotCrash() {
        // In high contrast mode, statusColor(highContrast:true) should not crash
        let _ = BlockPlaceholderStatus.unfilled.statusColor(highContrast: true)
        let _ = BlockPlaceholderStatus.partial.statusColor(highContrast: true)
        let _ = BlockPlaceholderStatus.complete.statusColor(highContrast: true)
        let _ = BlockPlaceholderStatus.unfilled.statusColor(highContrast: false)
        let _ = BlockPlaceholderStatus.partial.statusColor(highContrast: false)
        let _ = BlockPlaceholderStatus.complete.statusColor(highContrast: false)
    }

    // MARK: - Test 6: PromptStudioModel has announceCanvasChange method

    func test_promptStudioModel_announceCanvasChange_doesNotCrash() async throws {
        try await MainActor.run {
            let context = try TestHelpers.makeTestModelContext()
            let prompt = Prompt(title: "Test", content: "")
            context.insert(prompt)
            let model = PromptStudioModel(prompt: prompt)

            // announceCanvasChange must exist and not crash
            model.announceCanvasChange("Test announcement: 3 blocks on canvas.")
        }
    }

    // MARK: - Test 7: PlaceholderStatus.calculate with no placeholders returns complete

    func test_placeholderStatus_calculate_withNoPlaceholders_returnsComplete() {
        let status = BlockPlaceholderStatus.calculate(snippet: "STATIC CONTENT", inputs: [:])
        XCTAssertEqual(status, .complete)
    }

    // MARK: - Test 8: PlaceholderStatus.calculate with unfilled placeholders returns unfilled

    func test_placeholderStatus_calculate_withUnfilledPlaceholders_returnsUnfilled() {
        let status = BlockPlaceholderStatus.calculate(snippet: "ROLE: {{role}}", inputs: [:])
        XCTAssertEqual(status, .unfilled)
    }

    // MARK: - Test 9: PlaceholderStatus.calculate with partial inputs returns partial

    func test_placeholderStatus_calculate_withPartialInputs_returnsPartial() {
        let status = BlockPlaceholderStatus.calculate(
            snippet: "ROLE: {{role}}\nPRIORITY: {{priority}}",
            inputs: ["role": "Engineer"]
        )
        XCTAssertEqual(status, .partial)
    }

    // MARK: - Test 10: Canvas accessibility summary string format

    func test_canvasAccessibilitySummary_formatIsCorrect() {
        // Verify the format used in CompositionCanvasView accessibilityLabel
        let blockCount = 5
        let label = "Composition canvas, \(blockCount) block\(blockCount == 1 ? "" : "s")"
        XCTAssertEqual(label, "Composition canvas, 5 blocks")

        let singleLabel = "Composition canvas, \(1) block\(1 == 1 ? "" : "s")"
        XCTAssertEqual(singleLabel, "Composition canvas, 1 block")
    }
}
